Prepare release r1.2
camaraproject/DeviceSwap pull request #31
Opened 2024-12-10 09:35 UTC by jgarciahospital

#### What type of PR is this?

* subproject management

#### What this PR does / why we need it:
Prepare the release 1.2 with the required changes.

#### Which issue(s) this PR fixes:

Fixes #20

2024-12-11 17:12 UTC, bigludo7 submitted a review, later dismissed
LGTM

2024-12-12 10:00 UTC, hdamker requested changes

2024-12-12 10:00 UTC, hdamker commented on CHANGELOG.md
> +**device-swap v0.1.0 is the 1st release of the version 0.1.0**
There will be only one release of this version

```suggestion
**device-swap v0.1.0 is the public release of the version 0.1.0**
```

2024-12-12 10:00 UTC, hdamker commented on CHANGELOG.md
> +  - [View it on Swagger Editor](https://editor.swagger.io/?url=https://raw.githubusercontent.com/camaraproject/DeviceSwap/blob/r1.2/code/API_definitions/device-swap.yaml)
These links won't work with the "blob"

```suggestion
  - [View it on ReDoc](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/camaraproject/DeviceSwap/r1.2/code/API_definitions/device-swap.yaml&nocors)
  - [View it on Swagger Editor](https://editor.swagger.io/?url=https://raw.githubusercontent.com/camaraproject/DeviceSwap/r1.2/code/API_definitions/device-swap.yaml)
```

NOTE: The same change has to be done within r1.1, the links for Redoc and Swagger there are not working.

2024-12-12 10:00 UTC, hdamker commented on README.md
> +* The release r1.2 contains the version 0.1.0 of the Device Swap API. It is the release of the v0.1.0. The release tag is [r1.2](https://github.com/camaraproject/DeviceSwap/tree/r1.2).
Second sentence looks like a duplicate to me:

```suggestion
* The release r1.2 contains the version 0.1.0 of the Device Swap API. The release tag is [r1.2](https://github.com/camaraproject/DeviceSwap/tree/r1.2).
```

2024-12-12 10:01 UTC, hdamker commented
@jgarciahospital one needed correction and two suggestions, see above

2024-12-12 10:09 UTC, jgarciahospital commented
Thanks @hdamker, correction included (also in r1.1) and suggestions merged.

2024-12-12 15:36 UTC, bigludo7 approved these changes
LGTM !

2024-12-12 16:37 UTC, merged